### ISSUE TITLE
ERROR 1273 (HY000) at line 325: Unknown collation: 'utf8mb4_0900_ai_ci'

### ISSUE THREAD

**Issue by pokapow** [back2arie/Kalkun#190]
When import new mysql_kalkun.sql:

`ERROR 1273 (HY000) at line 325: Unknown collation: 'utf8mb4_0900_ai_ci'`

**Solution:**

Replace the string “_utf8mb4_0900_ai_ci_” by “_utf8mb4_general_ci_“.

**Comment by tenzap** [comment]
According to https://stackoverflow.com/a/44877331
`utf8mb4_0900_ai_ci` requires **MySQL/MariaDB 5.6** (available since February 5, 2013, supported until Feb/2021)
So upgrading the mysql server is another solution.

BTW, MySQL 5.5 End of Support was  December 2018
https://en.wikipedia.org/wiki/MySQL#Release_history

**Comment by tenzap** [comment]
Should be fixed in #211
