### ISSUE TITLE
404 for all installed plugin

### ISSUE THREAD

**Issue by pokapow** [back2arie/Kalkun#191]
Whatever plugin I install, I get a 404 when I try to go to it once installed.
Also, on the available plugins page (index.php/pluginss/index/available) of php error displays:

```
A PHP Error was encountered
Severity: Warning

Message: include_once(): Failed opening '/var/www/kalkun/plugins//rest_api/rest_api.php' for inclusion (include_path='.:/usr/share/php')

Filename: libraries/Plugins.php

Line Number: 173
```

Is pluginSS with 2 "s" in url of plugin page normal ?

**Comment by kingster** [comment]
yes, this is a known error. this happened after #187 which supports php7.x.

We are working on fixing this issue.

**Comment by pandigresik** [comment]
please check my PR #192

**Comment by tenzap** [comment]
I also had a 404-Error issue for the plugins.
Your PR didn't fix my issue, but PR #199 does.

**Comment by tenzap** [comment]
Moreover it seems most 404-error issues for plugins seems to be due to the fact that the filename of their controller in `plugins/<plugin_name>/controllers/` is simply not "Ucfirst-ed" (first letter upper-case) which is a requirements with ci3 https://codeigniter.com/userguide3/installation/upgrade_300.html#step-2-update-your-classes-file-names

**Comment by tenzap** [comment]
Migration of all plugins is in PR #200 
+ also revert of PR #192 in #207 (because it creates bug #206 and is not necessary to have plugins work)
