### ISSUE TITLE
No available plugins

### ISSUE THREAD

**Issue by ebasse-prog** [back2arie/Kalkun#481]
I have plugins Kalkun\application\plugins\rest_api in the appropriate folder, but I do not have them on the list to be installed.
Why? Do i need to configure anything extra?

![obraz](https://user-images.githubusercontent.com/65177524/196672739-4d6ec3a4-6f19-4eb6-8b60-9e7e644b6ba0.png)

**Comment by tenzap** [comment]
Please follow the issue template and report the content of About screen, as well as the detailed steps of how you installed.

Otherwise, for usage of Rest-Api check: https://github.com/kalkun-sms/Kalkun/wiki/Plugin%3A-REST-Api
For installation instructions, check: https://github.com/kalkun-sms/Kalkun/wiki/Installation (check also the requirements).

**Comment by tenzap** [comment]
Closing since there has been no additional info provided.
Feel free to reopen if you can provide additional information.
